In [32]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('test_tradebook.csv')

def avg_price(row):
    return pd.Series([sum(row.back_trades['p'])/len(row.back_trades['p']) if len(row.back_trades['p']) > 0 else 0, sum(row.lay_trades['p'])/len(row.lay_trades['p']) if len(row.lay_trades['p']) > 0 else 0])

def total_volume(row):
    return pd.Series([sum(row.back_trades['v']), sum(row.lay_trades['v'])])

In [34]:
import ast
df['back_trades'] = [ast.literal_eval(x) for x in df['back_trades']]
df['lay_trades'] = [ast.literal_eval(x) for x in df['lay_trades']]

df[['avg_back_price', 'avg_lay_price']] = df.apply(lambda row: avg_price(row), axis=1, result_type='expand')
df[['back_vol', 'lay_vol']] = df.apply(lambda row: total_volume(row), axis=1, result_type='expand')
df

,Unnamed: 0,selection_id,selection_name,back_trades,lay_trades,lay_v_sum,back_v_sum,avg_back_price,avg_lay_price,back_vol,lay_vol
0,0,64318416,1. Border Leicester,"{'p': [8.4, 9.4, 9.4, 9.2, 9.4, 9.0, 9.0, 8.6,...","{'p': [8.6, 8.6, 9.6, 9.4, 9.4, 9.4, 8.6, 8.6,...",13,177,7.308475,8.738462,177,13
1,1,26982063,8. Serenade The Stars,"{'p': [100.0, 110.0, 110.0, 100.0, 100.0, 100....","{'p': [100.0, 100.0, 100.0, 100.0, 100.0, 100....",25,40,103.250000,99.800000,40,25
2,2,28092060,7. Guns Ablazing,"{'p': [8.2, 8.2, 8.2, 8.2], 'v': [1, 1, 1, 1]}","{'p': [7.8, 7.8, 7.6, 7.2], 'v': [1, 1, 1, 1]}",4,4,8.200000,7.600000,4,4
3,3,6465237,6. Bon Appetit,"{'p': [5.9, 5.8, 5.9, 5.8, 5.9, 5.9, 6.0, 6.0,...","{'p': [7.0, 6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 6.6,...",75,421,6.995249,6.536000,421,75
4,4,23947555,4. Flambeur,"{'p': [13.5, 13.5, 13.5, 13.5, 13.5, 13.5, 13....","{'p': [17.0, 15.5, 15.0, 15.0, 15.0, 15.0, 15....",201,92,14.168478,14.621891,92,201
5,5,36894802,3. Mr Blackwood,"{'p': [26.0, 26.0, 26.0, 26.0, 21.0, 18.0, 19....","{'p': [24.0, 24.0, 24.0, 24.0, 22.0, 20.0, 20....",38,263,18.990494,18.473684,263,38
6,6,66294934,2. Galilaeus,"{'p': [2.18, 2.22, 2.2, 2.24, 2.1, 2.14, 2.14,...","{'p': [2.24, 2.14, 2.1, 2.12, 2.26, 2.26, 2.26...",27,502,2.345697,2.249630,502,27
7,7,41510961,9. Sir Peter,"{'p': [55.0, 60.0, 60.0, 70.0, 70.0, 80.0, 70....","{'p': [75.0, 75.0, 70.0, 65.0, 55.0, 70.0, 70....",69,112,73.660714,61.014493,112,69